version: "3.7"
services:
  spring:
    container_name: moa-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ~/ichubtou/docker/moa:/logs/
    environment:
      MOA_SERVER: ${MOA_SERVER}
      MOA_AWS_ACCESS_KEY: ${MOA_AWS_ACCESS_KEY}
      MOA_AWS_SECRET_KEY: ${MOA_AWS_SECRET_KEY}
      MOA_AWS_PATH_STYLE_ACCESS: ${MOA_AWS_PATH_STYLE_ACCESS}
      MOA_AWS_BUCKET_NAME: ${MOA_AWS_BUCKET_NAME}
      MOA_AWS_ENDPOINT_URL: ${MOA_AWS_ENDPOINT_URL}
      MOA_AWS_REGION: ${MOA_AWS_REGION}
      MOA_NAVER_CLIENT_ID: ${MOA_NAVER_CLIENT_ID}
      MOA_NAVER_CLIENT_SECRET: ${MOA_NAVER_CLIENT_SECRET}
      MOA_KAKAO_CLIENT_ID: ${MOA_KAKAO_CLIENT_ID}
      MOA_KAKAO_CLIENT_SECRET: ${MOA_KAKAO_CLIENT_SECRET}}
      MOA_DB_ENDPOINT: ${MOA_DB_ENDPOINT}
      MOA_DB_NAME: ${MOA_DB_NAME}
      MOA_DB_ID: ${MOA_DB_ID}
      MOA_DB_PASSWORD: ${MOA_DB_PASSWORD}
      MOA_JWT_SECRET_KEY: ${MOA_JWT_SECRET_KEY}
      MOA_ACCESS_TOKEN_EXP: ${MOA_ACCESS_TOKEN_EXP}
      MOA_REFRESH_TOKEN_EXP: ${MOA_REFRESH_TOKEN_EXP}
      MOA_GOOGLE_CLIENT_ID: ${MOA_GOOGLE_CLIENT_ID}
      MOA_GOOGLE_CLIENT_SECRET: ${MOA_GOOGLE_CLIENT_SECRET}