version: "3.7"
services:
  spring:
    container_name: moa-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ~/ichubtou/docker/moa/logs:/logs/
    environment:
      MOA_SERVER: ${MOA_SERVER}
      MOA_AWS_ACCESS_KEY: ${MOA_AWS_ACCESS_KEY}
      MOA_AWS_SECRET_KEY: ${MOA_AWS_SECRET_KEY}
      MOA_AWS_PATH_STYLE_ACCESS: ${MOA_AWS_PATH_STYLE_ACCESS}
      MOA_AWS_BUCKET_NAME: ${MOA_AWS_BUCKET_NAME}
      MOA_AWS_ENDPOINT_URL: ${MOA_AWS_ENDPOINT_URL}
      MOA_AWS_REGION: ${MOA_AWS_REGION}
      MOA_NAVER_CLIENT_ID: ${MOA_NAVER_CLIENT_ID}
      MOA_NAVER_CLIENT_SECRET: ${MOA_NAVER_CLIENT_SECRET}
      MOA_KAKAO_CLIENT_ID: ${MOA_KAKAO_CLIENT_ID}
      MOA_KAKAO_CLIENT_SECRET: ${MOA_KAKAO_CLIENT_SECRET}}
      MOA_DB_ENDPOINT: ${MOA_DB_ENDPOINT}
      MOA_DB_NAME: ${MOA_DB_NAME}
      MOA_DB_ID: ${MOA_DB_ID}
      MOA_DB_PASSWORD: ${MOA_DB_PASSWORD}
      MOA_JWT_SECRET_KEY: ${MOA_JWT_SECRET_KEY}
      MOA_ACCESS_TOKEN_EXP: ${MOA_ACCESS_TOKEN_EXP}
      MOA_REFRESH_TOKEN_EXP: ${MOA_REFRESH_TOKEN_EXP}
      MOA_GOOGLE_CLIENT_ID: ${MOA_GOOGLE_CLIENT_ID}
      MOA_GOOGLE_CLIENT_SECRET: ${MOA_GOOGLE_CLIENT_SECRET}
    labels:
      - "traefik.http.routers.spring.rule=Host(`moa.ichubtou.com`)"
      - "traefik.http.routers.spring.entrypoints=websecure"
      - "traefik.http.routers.spring.tls.certresolver=myresolver"
      - "traefik.http.services.spring.loadbalancer.server.port=8081"
      - "traefik.http.routers.spring-secure.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
    networks:
      - traefik-network
networks:
  traefik-network:
    external: true