server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: moa
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${MOA_GOOGLE_CLIENT_ID}
            client-secret: ${MOA_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          kakao:
            client-id: ${MOA_KAKAO_CLIENT_ID}
            client-secret: ${MOA_KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            client-name: kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
          naver:
            client-id: ${MOA_NAVER_CLIENT_ID}
            client-secret: ${MOA_NAVER_CLIENT_SECRET}
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            client-name: naver
            authorization-grant-type: authorization_code
            scope:
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
  datasource:
    url: jdbc:mysql://${MOA_DB_ENDPOINT}/${MOA_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MOA_DB_ID}
    password: ${MOA_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        highlight_sql: true
        format_sql: true
        use_sql_comments: true

jwt:
  key: ${MOA_JWT_SECRET_KEY}
  access-token-expiration-minutes: ${MOA_ACCESS_TOKEN_EXP}
#  refresh-token-expiration-minutes: ${MOA_REFRESH_TOKEN_EXP}