server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: moa

  datasource:
    url: jdbc:mysql://${MOA_DB_ENDPOINT}/${MOA_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MOA_DB_ID}
    password: ${MOA_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        highlight_sql: true
        format_sql: true
        use_sql_comments: true

jwt:
  key: ${MOA_JWT_SECRET_KEY}
  access-token-expiration-minutes: ${MOA_ACCESS_TOKEN_EXP}
#  refresh-token-expiration-minutes: ${MOA_REFRESH_TOKEN_EXP}